name: "Action: Clear all GHA caches"
on:
  workflow_dispatch:
    inputs:
      clear_pending:
        description: Delete caches of pending workflows
        type: boolean
        default: false
      clear_develop:
        description: Delete caches on develop branch
        type: boolean
        default: false
      clear_branches:
        description: Delete caches on non-develop branches
        type: boolean
        default: true
  schedule:
    # Run every day at midnight
    - cron: '0 0 * * *'

jobs:
  clear-caches:
    name: Delete all caches
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Clear caches
        uses: ./dev-packages/clear-cache-gh-action
        with:
          clear_pending: ${{ inputs.clear_pending }}
          clear_develop: ${{ inputs.clear_develop }}
          clear_branches: ${{ inputs.clear_branches }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
